.PHONY: clean All

All:
	@echo "----------Building project:[ SmartPointers_Challenge1 - Debug ]----------"
	@cd "SmartPointers_Challenge1" && "$(MAKE)" -f  "SmartPointers_Challenge1.mk"
clean:
	@echo "----------Cleaning project:[ SmartPointers_Challenge1 - Debug ]----------"
	@cd "SmartPointers_Challenge1" && "$(MAKE)" -f  "SmartPointers_Challenge1.mk" clean
