.PHONY: clean All

All:
	@echo "----------Building project:[ cppStyle - Debug ]----------"
	@cd "cppStyle" && "$(MAKE)" -f  "cppStyle.mk"
clean:
	@echo "----------Cleaning project:[ cppStyle - Debug ]----------"
	@cd "cppStyle" && "$(MAKE)" -f  "cppStyle.mk" clean
