.PHONY: clean All

All:
	@echo "----------Building project:[ Exceptions_Challenge - Debug ]----------"
	@cd "Exceptions_Challenge" && "$(MAKE)" -f  "Exceptions_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Exceptions_Challenge - Debug ]----------"
	@cd "Exceptions_Challenge" && "$(MAKE)" -f  "Exceptions_Challenge.mk" clean
