.PHONY: clean All

All:
	@echo "----------Building project:[ Stream_ManipBool - Debug ]----------"
	@cd "Streams_Manip" && "$(MAKE)" -f  "Stream_ManipBool.mk"
clean:
	@echo "----------Cleaning project:[ Stream_ManipBool - Debug ]----------"
	@cd "Streams_Manip" && "$(MAKE)" -f  "Stream_ManipBool.mk" clean
