.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeExternalFunctions - Debug ]----------"
	@cd "ChallengeMemberFunctions" && "$(MAKE)" -f  "ChallengeExternalFunctions.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeExternalFunctions - Debug ]----------"
	@cd "ChallengeMemberFunctions" && "$(MAKE)" -f  "ChallengeExternalFunctions.mk" clean
