.PHONY: clean All

All:
	@echo "----------Building project:[ primitives - Debug ]----------"
	@cd "primitives" && "$(MAKE)" -f  "primitives.mk"
clean:
	@echo "----------Cleaning project:[ primitives - Debug ]----------"
	@cd "primitives" && "$(MAKE)" -f  "primitives.mk" clean
