.PHONY: clean All

All:
	@echo "----------Building project:[ AllocArrayInsideFunc - Debug ]----------"
	@cd "AllocArrayInsideFunc" && "$(MAKE)" -f  "AllocArrayInsideFunc.mk"
clean:
	@echo "----------Cleaning project:[ AllocArrayInsideFunc - Debug ]----------"
	@cd "AllocArrayInsideFunc" && "$(MAKE)" -f  "AllocArrayInsideFunc.mk" clean
