.PHONY: clean All

All:
	@echo "----------Building project:[ Polimorphism_Challenge - Debug ]----------"
	@cd "Polimorphism_Challenge" && "$(MAKE)" -f  "Polimorphism_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Polimorphism_Challenge - Debug ]----------"
	@cd "Polimorphism_Challenge" && "$(MAKE)" -f  "Polimorphism_Challenge.mk" clean
