.PHONY: clean All

All:
	@echo "----------Building project:[ first_programm - Debug ]----------"
	@cd "first_programm" && "$(MAKE)" -f  "first_programm.mk"
clean:
	@echo "----------Cleaning project:[ first_programm - Debug ]----------"
	@cd "first_programm" && "$(MAKE)" -f  "first_programm.mk" clean
