.PHONY: clean All

All:
	@echo "----------Building project:[ refresh - Debug ]----------"
	@cd "refresh" && "$(MAKE)" -f  "refresh.mk"
clean:
	@echo "----------Cleaning project:[ refresh - Debug ]----------"
	@cd "refresh" && "$(MAKE)" -f  "refresh.mk" clean
