.PHONY: clean All

All:
	@echo "----------Building project:[ _FrankMovies - Debug ]----------"
	@cd "_FrankMovies" && "$(MAKE)" -f  "_FrankMovies.mk"
clean:
	@echo "----------Cleaning project:[ _FrankMovies - Debug ]----------"
	@cd "_FrankMovies" && "$(MAKE)" -f  "_FrankMovies.mk" clean
