.PHONY: clean All

All:
	@echo "----------Building project:[ compare - Debug ]----------"
	@cd "compare" && "$(MAKE)" -f  "compare.mk"
clean:
	@echo "----------Cleaning project:[ compare - Debug ]----------"
	@cd "compare" && "$(MAKE)" -f  "compare.mk" clean
