.PHONY: clean All

All:
	@echo "----------Building project:[ range_based_loop - Debug ]----------"
	@cd "range_based_loop" && "$(MAKE)" -f  "range_based_loop.mk"
clean:
	@echo "----------Cleaning project:[ range_based_loop - Debug ]----------"
	@cd "range_based_loop" && "$(MAKE)" -f  "range_based_loop.mk" clean
