.PHONY: clean All

All:
	@echo "----------Building project:[ math_lib - Debug ]----------"
	@cd "math_lib" && "$(MAKE)" -f  "math_lib.mk"
clean:
	@echo "----------Cleaning project:[ math_lib - Debug ]----------"
	@cd "math_lib" && "$(MAKE)" -f  "math_lib.mk" clean
